### ISSUE TITLE
Remove Google Analytics

### ISSUE THREAD

**Issue by alexesprit** [web-scrobbler/web-scrobbler#2429]
I find data tracking pretty useless for me, so removing this feature could be good for me (I don't need to maintain GA related code) and for users (their data won't be tracked by the extension).

Ref: https://gist.github.com/alexesprit/3e3361550da08273e7b6d9f5e9c5d8ce.

## Tasks to do

- [x] Remove GA-related code
- [x] Update privacy policy
- [ ] Translate privacy policy

**Comment by alexesprit** [comment]
> How else can we see how well adopted the extension is through the marketplaces without?

GA does not give you this information.

> I mean it's opt in on install now?

Now tracking data is enabled by default, and can be disabled either via startup page after the extension installation, or via the options page later.

**Comment by inverse** [comment]
> GA does not give you this information.

Yes it does - it shows you how many current users are using the extension

> Now tracking data is enabled by default, and can be disabled either via startup page after the extension installation, or via the options page later.

You mean for current installs? 

I think having some form of telemetry is a good thing to be able to best shape the product. e.g. which connectors people use, interactions etc. How else will you know these patterns without telemetry?

**Comment by alexesprit** [comment]
Like I said, I see no benefits of using telemetry.

Now the extension collects connector injects, and scrobble events. It also uses a `pageview` event, so we can view how many users are using the extension right now (not sure if it's a correct number, btw). *How* do you use this data?

> I think having some form of telemetry is a good thing to be able to best shape the product. e.g. which connectors people use, interactions etc. How else will you know these patterns without telemetry?

You're talking about what data is collected, but how do suggest to use it?

I'm not against keeping GA, but when there's no sense to use it, it's better to get rid of collecting data.

**Comment by peacegiverman** [comment]
Had this done locally some time ago, so I just submited a pull requested.

**Comment by inverse** [comment]
> You're talking about what data is collected, but how do suggest to use it?

I'll try to take a look when I have some time but I think It'll be interesting to get metrics on things like how much usage each connector is getting or per browser breakdowns etc.

**Comment by jbwharris** [comment]
Have Analytics been straight up removed from Web Scrobbler? I am definitely curious as to data about which are the most popular connectors and inversely which aren't being used. Having done work on the SiriusXM connector recently I'm curious how many people use it regularly. I think it is used a fair bit, given the last.fm data, but there's no dates or anything tied to that historical data, just how many users might have mis-scrobbled a station tag. 

** Cases data would be interesting
1. Seeing which connectors are popular, even if to just verify the connector works well. I know users don't always report issues. 
2. Where people are actually listening to music. I'm someone who likes to explore, so the idea users might be clustering around a service/radio station I was unaware of would be insightful.
3. Which connectors aren't being used? Are they potentially broken and nobody has said anything, if say there are pageviews for a given service, but no scrobbles are coming from the site? That would imply an issue.
