### ISSUE TITLE
Publish to MS Edge Addons, take 2

### ISSUE THREAD

**Issue by alexesprit** [web-scrobbler/web-scrobbler#2525]
## Tasks to do

- [x] Add notes from https://github.com/web-scrobbler/web-scrobbler/issues/678#issuecomment-671879812 to the wiki
- [x] Submit the extension again and provide the link to notes and the test account
- [ ] (Optional) Find a way to publish the extension automatically

Ref #678.

**Comment by inverse** [comment]
Good luck @alexesprit :crossed_fingers:

**Comment by alexesprit** [comment]
Added the notes to the wiki: https://github.com/web-scrobbler/web-scrobbler/wiki/Notes-for-certification. I allowed editing wiki for everyone, so feel free to update this page.

**Comment by alexesprit** [comment]
![image](https://user-images.githubusercontent.com/1119267/90491986-54cffb00-e149-11ea-96d1-d2199947d757.png)

**Comment by alexesprit** [comment]
I provided a URL to the notes for certification. Seems like they didn't read them. :( That's really sad.

Should I provide the notes as a text instead?

**Comment by inverse** [comment]
Anything to make it easier for them...


I remember going through this madness with Samsung app store approvals.

Anything that makes it clearer helps.

**Comment by alexesprit** [comment]
I will upload the next version with notes for certification added as a text, and video included. We'll see if it helps to pass the review.

Btw, we have a sort of "Get started" video, but it's outdated a little since we updated UI, and added multiscrobbling.

> I remember going through this madness with Samsung app store approvals.

I  thought publishing the extension to AMO was madness. :D How wrong i was...

**Comment by alexesprit** [comment]
I've submitted v2.36.0.

**Comment by alexesprit** [comment]
I was really surprised this morning.

![image](https://user-images.githubusercontent.com/1119267/94358894-b3738780-00ac-11eb-94b8-ca9657640193.png)

**Comment by inverse** [comment]
Success!

**Comment by alexesprit** [comment]
It does not mean the extension is published, but it should be available in the store soon:

> Your extension has passed all validations and it will be published to Microsoft Edge Addons store soon. The publishing process typically takes a few hours although submission volume / server maintenance may cause additional delays.

I will post a link to the store page here when it will be available.

**Comment by alexesprit** [comment]
https://microsoftedge.microsoft.com/addons/detail/web-scrobbler/obiekdelmkmlgnhddmmnpnfhngejbnnc

**Comment by hans-juergen** [comment]
Nice, while checking installed extensions in Edge I just noticed that Web Scrobbler is now available in the MS Store, too. 👍 Anyone adding this should note that you have to authenticate to your Last.fm account again with the new version of course, and that you do not need the Chrome version anymore in Edge, so you can remove it.

**Comment by alexesprit** [comment]
> Anyone adding this should note that you have to authenticate to your Last.fm account again with the new version of course, and that you do not need the Chrome version anymore in Edge, so you can remove it.

Sure, it's installed as a separate extension.

**Comment by inverse** [comment]
Awesome work for all those that helped!
